### PR TITLE
Introduce tox to handle unit testing.

### PR DESCRIPTION
**Pull request by 4383**
Manage unit test with:
- tox to unify usage between kind of test (unit test, future pep8 tests etc...)
- stestr to parallelize unit test execution and save time, to measure duration, etc...

Signed-off-by: Hervé Beraud <hberaud@redhat.com>

### CODE REVIEW

**Comment by haraldh** [comment]
seems like travis has failed

**Comment by 4383** [comment]
@haraldh yeah I also added coverage to tox.

**Comment by haraldh** [comment]
still fails

**Comment by 4383** [comment]
yeah error little bit different I need to inspect

**Comment by 4383** [comment]
Some python 3 imports causes errors on python 2.7 CI (`builtins`)

**Comment by 4383** [comment]
closed by error

**Pull request merged**
