### PR TITLE
Allow user to define mocked types

### PR DESCRIPTION
**Pull request by 4383**
To introduce more complex mocking features allow user to define
mocked types.

### CODE REVIEW

**Comment by 4383** [comment]
https://github.com/varlink/python/pull/16 will fix the CI error there.

**Comment by 4383** [comment]
Thanks, can you release a new version on pypi to unblock podman side too. 

Thank you.

**Comment by haraldh** [comment]
tagged 30.3.0 ... let's see, if the travis deploy works

**Comment by haraldh** [comment]
Yay! worked :)

**Comment by 4383** [comment]
Great! Thank you @haraldh!

**Pull request merged**
